Repository DrakeHunterK7/SOEN-341-Fall-2021-Team-9-Stack-Bubbling-, pull requests merged in 2021-11, with the labels that each got.

#106 Travis ci backend setup
  .travis.yml
  backend-stack-bubbling/app.py
  backend-stack-bubbling/requirements.txt
  backend-stack-bubbling/test_app.py
Labels: Testing

#117 #102 display question page
  backend-stack-bubbling/test_app.py
  frontend-stack-bubbling/src/components/AnswerBox/index.jsx
  frontend-stack-bubbling/src/components/Header/index.css
  frontend-stack-bubbling/src/components/Header/index.jsx
  frontend-stack-bubbling/src/components/QuestionBox/index.jsx
  frontend-stack-bubbling/src/components/QuestionPreviewTemplate/index.css
  frontend-stack-bubbling/src/components/QuestionPreviewTemplate/index.jsx
  frontend-stack-bubbling/src/pages/Home/PostQuestion/index.jsx
  frontend-stack-bubbling/src/pages/QuestionTemplatePage/index.css
  frontend-stack-bubbling/src/pages/QuestionTemplatePage/index.jsx
Labels: Task, High Risk High Value, 3 points, Priority: High

#108 #73 Backend List All My Questions
  backend-stack-bubbling/app.py
  backend-stack-bubbling/test_app.py
Labels: Backend, Task

#120 #75 Backend List All My Answers Implemented
  backend-stack-bubbling/app.py
Labels: Database, Backend

#122 Added Vote Buttons to Questions and Answers
  backend-stack-bubbling/__pycache__/app.cpython-39.pyc
  frontend-stack-bubbling/src/DownvoteHover.png
  frontend-stack-bubbling/src/Downvoted.png
  frontend-stack-bubbling/src/NormalDownvote.png
  frontend-stack-bubbling/src/NormalUpvote.png
  frontend-stack-bubbling/src/UpvoteHover.png
  frontend-stack-bubbling/src/Upvoted.png
  frontend-stack-bubbling/src/components/AnswerBox/index.css
  frontend-stack-bubbling/src/components/AnswerBox/index.jsx
  frontend-stack-bubbling/src/components/QuestionBox/index.jsx
  frontend-stack-bubbling/src/components/QuestionPreviewTemplate/index.jsx
  frontend-stack-bubbling/src/pages/Home/QuestionList/index.jsx
  frontend-stack-bubbling/src/pages/QuestionTemplatePage/index.jsx
Labels: Frontend, High Risk High Value, 2 points, Priority: High

#121 #109 - Improve ListAnswers Function
  backend-stack-bubbling/app.py
Labels: enhancement

#123 #66 question and answer voting
  backend-stack-bubbling/__pycache__/app.cpython-39.pyc
  backend-stack-bubbling/app.py
  frontend-stack-bubbling/src/BestAnswerNormal.png
  frontend-stack-bubbling/src/components/AnswerBox/index.css
  frontend-stack-bubbling/src/components/AnswerBox/index.jsx
  frontend-stack-bubbling/src/components/QuestionBox/index.jsx
  frontend-stack-bubbling/src/components/QuestionPreviewTemplate/index.jsx
  frontend-stack-bubbling/src/pages/Home/PostQuestion/index.jsx
  frontend-stack-bubbling/src/pages/QuestionTemplatePage/index.jsx
Labels: 5 points

#124 # 111 Backend Notifications of Questions implemented
  backend-stack-bubbling/app.py
Labels: Database, Backend

#126 [BugFix] Notifications should count vote_change of "VoteAnswer" and "VoteQuestion"
  backend-stack-bubbling/app.py
Labels: bug
